### ISSUE TITLE
typo in repo description

### ISSUE THREAD

**Issue by arthurvr** [kevva/is-exe#1]
the current repo description is:

> Check if a Buffer/Uint8Array is a EXE fil

you're missing an `e` at the end.

**Comment by kevva** [comment]
Where?

**Comment by arthurvr** [comment]
![kevva_is-exe](https://cloud.githubusercontent.com/assets/6025224/6546488/6559e054-c5b5-11e4-9d63-d7fb90c16124.png)

**Comment by kevva** [comment]
Ah, didn't see! Thanks.
